spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/yjpfj1203/static-resource
                    search-paths: config-files
                    username: yjpfj1203@163.com
                    password: Liuhan1203